springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.oauth2-redirect-url=/swagger-ui/oauth2-redirect.html
server.forward-headers-strategy=framework